[package]
name = "enk"
version = "1.0.0"
edition = "2024"
authors = ["Ariel Horwitz <ariel.ninja>", "github.com/pepa65 <pepa65@passchier.net>"]
description = "Simple data en/decryption"
repository = "https://github.com/pepa65/enk"
documentation = "https://docs.rs/enk"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["cli", "encryption", "symmetric"]
categories = ["command-line-utilities"]

[package.metadata.binstall]
pkg-url = "{repo}/releases/download/{version}/enk"
pkg-fmt = "bin"
target = "x86_64-unknown-linux-musl"
disabled-strategies = ["quick-install", "compile"]
target-family = "Linux"
target-arch = "X86_64"

[dependencies]
aes-gcm = { version = "0.11", features = ["zeroize"] }
anyhow = "1"
argon2 = "0.6"
clap = { version = "4", features = ["derive"] }
console = "0.16"
rand = "0.10"
zeroize = "1"
